### PR TITLE
Added staging project to production workflows list

### PR DESCRIPTION
**Pull request by alexiswl**
Adding prod workflows to staging project. 

May need a manual transfer (via ACL hack) for existing workflows.

### CODE REVIEW

**Review by skanwal — COMMENTED** [review]
LGTM, thanks.

**Comment by alexiswl** [comment]
Ran the following command in the production_workflows context to add all workflows and workflow versions that currently exist in the production_workflows project and production project to also now exist in the staging project:

```bash
#!/usr/bin/env bash

# Set to fail
set -euo pipefail

# Globals
STAGING_PROJECT_ID="cid:c9173925-a838-4394-9fc6-61cb93c252a1"

# Step 1: Get all workflows in the production_workflows project
readarray -t workflows_array <<< "$(
    ica workflows list \
        --max-items=0 \
        --output-format=json | \
    jq --raw-output \
      '
        .items |
        map(
          select(
            .name | endswith("_prod-wf")
          )
        ) |
        map(.id) |
        .[]
      ' \
)"

# Step 2
# Iterate through workflow ids and update acls
for workflow_id in "${workflows_array[@]}"; do
  # Collect the current list of projects
  # as this needs to be appended to the list
  current_acls_str="$( \
    ica workflows get "${workflow_id}" \
      --output-format=json | \
    jq --raw-output \
      '
        .acl |
        map(
          select(
            startswith("cid:")
          )
        ) |
        join(",")
      ' \
  )"

  # Now update the workflow
  ica workflows update "${workflow_id}" \
    --acl "${current_acls_str},${STAGING_PROJECT_ID}"
done

# Step 3
# Now update the versions of the workflow ids

# Iterate through the workflow ids again
for workflow_id in "${workflows_array[@]}"; do
  # Step 3a
  # Collect the versions as an array
  readarray -t workflow_version_names_array <<< "$( \
    ica workflows versions list "${workflow_id}" \
      --output-format=json | \
    jq --raw-output \
      '
        .items |
        map(
          .version
        ) |
        .[]
      ' \
  )"

  # Step 3b
  # Iterate through each of the workflow versions for this workflow id
  # And update the acl on this workflow version
  for workflow_version_name in "${workflow_version_names_array[@]}"; do
    # Check workflow version name isn't empty
    if [[ -z "${workflow_version_name}" ]]; then
      continue
    fi
    # Collect the current list of projects
    # as this needs to be appended to the list
    current_acls_str="$( \
      ica workflows versions get "${workflow_id}" "${workflow_version_name}" \
        --output-format=json | \
      jq --raw-output \
        '
          .acl? |
          map(
            select(
              startswith("cid:")
            )
          ) |
          join(",")
        ' \
    )"

    # Now update the workflow
    ica workflows versions update "${workflow_id}" "${workflow_version_name}" \
      --acl "${current_acls_str},${STAGING_PROJECT_ID}"
  done
done
```

**Comment by alexiswl** [comment]
Wondering if we should also have a staging_workflows project, that way we can push workflows to staging without pushing them to production. All workflows in production will be available in staging, but not all workflows in staging will be available in production. Alternatively, we add the staging project to a 'linked project' of the development_workflows project?

**Comment by skanwal** [comment]
> but not all workflows in staging will be available in production.

Is there a good use case for this?

**Comment by alexiswl** [comment]
> Is there a good use case for this?

Yeah I think so, means a user can continue to push/sync/check etc workflows like we do in development in the staging project and test on staging data rather than requiring a pull request to do so.  However if the user then wants to merge a change into production they can deploy a production workflow into staging and have that be signed off.

**Comment by skanwal** [comment]
Okay, was just thinking in terms of complexity and duplication.

**Comment by alexiswl** [comment]
As discussed today, we could instead just link the staging project to the development workflows project instead.

**Comment by alexiswl** [comment]
@skanwal can this be approved now?

**Comment by skanwal** [comment]
@alexiswl - yes. Doing it now.

**Review by skanwal — APPROVED** [review]

**Pull request merged**
