### PR TITLE
Initialised new multiqc version (1.14.0)

### PR DESCRIPTION
**Pull request by alexiswl**
## Description

New cwltool for multiqc 1.14.0

## TODO

- [x] Wait for #202 
- [x] Wait for #185

### CODE REVIEW

**Comment by ohofmann** [comment]
@alexiswl Do we have a before/after MultiQC report for one or more of the validation samples? Given the whole merge history it would be good to confirm that the key metrics are still present (and match between versions).

**Comment by alexiswl** [comment]
> Given the whole merge history it would be good to confirm that the key metrics are still present (and match between versions).

Yep we can certainly run this on some validation samples and have added that to the to-do list in https://github.com/umccr/cwl-ica/pull/232

**Comment by skanwal** [comment]
@alexiswl - are you happy for this to be reviewed? 
Did you test the CWL definition (not the report) to confirm this new multiQC tag works?

**Comment by alexiswl** [comment]
> Did you test the CWL definition (not the report) to confirm this new multiQC tag works?

Yes have run the cwltool locally and works fine.  

Only discrepancy I see between the versions is that if a multiqc 'General Stat' value is NA, it will not appear in the General Stats table. This is often the case for the "Contam'n" stat and can be traced back to [this commit](https://github.com/ewels/MultiQC/commit/63b270afa37550ef4d9ad241fef6051c67b6fdbe)

**Review by skanwal — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
