### PR TITLE
Move bclconvert v3.7.5 container to ghcr.io

### LINKED ISSUE #181: Consider ghcr for bclconvert 3.7.5

### PR DESCRIPTION
**Pull request by alexiswl**
All future versions are already in this repo.

Resolves #181

### CODE REVIEW

**Comment by skanwal** [comment]
Linking for convenience https://github.com/umccr/docker-who/pkgs/container/bcl-convert

**Review by skanwal — APPROVED** [review]
LGTM. Adding a link for reference https://github.com/umccr/docker-who/pkgs/container/bcl-convert

**Comment by skanwal** [comment]
Ugh, sync command still failing..

**Comment by alexiswl** [comment]
> Ugh, sync command still failing..

No I cancelled it, had another sync command running in parallel, would rather rebase onto master and then re-run to reduce merge conflicts.

**Pull request merged**
