### PR TITLE
Updated sync tools and sync workflows to use AWS creds instead

### PR DESCRIPTION
**Pull request by alexiswl**
Credentials now expire in 24 hours so use creds from AWS instead

### CODE REVIEW

**Comment by skanwal** [comment]
@alexiswl - do we also need to get staging workflows project token?

**Comment by alexiswl** [comment]
Nope, since we never went with staging workflows project, just development_workflows and production_workflows push into the staging project

**Comment by alexiswl** [comment]
Ran the sync command and looks like it can create workflows in dev and prod so that's a win.  

Looking into why so many workflow definitions in project.yaml updated without the workflow.yaml or tool.yaml updating https://github.com/umccr/cwl-ica-cli/issues/42

**Comment by skanwal** [comment]
Huh.. one for discussion tomorrow.

**Review by skanwal — APPROVED** [review]
LGTM. Project yaml update to be discussed tomorrow.

**Comment by alexiswl** [comment]
Yep, fixing https://github.com/umccr/cwl-ica-cli/issues/42 has resolved the sync issues

**Pull request merged**
