### PR TITLE
Added umccrise-pipeline versions 2.2.0 and 2.2.1

### LINKED ISSUE #247: Make workflows for UMCCRise and RNASum
UMCCRise and RNASum are CommandLineTools, to allow for pack / zip tag deployment, we need them to be workflows. 

Obvious solution is to make single step workflows for each.

### PR DESCRIPTION
**Pull request by alexiswl**
Single step workflows that call the umccrise tool

Partially fixes #247

### CODE REVIEW

**Review by skanwal — APPROVED** [review]
LGTM, thanks.

**Comment by alexiswl** [comment]
Ah very weird [e429468](https://github.com/umccr/cwl-ica/pull/248/commits/e429468624521e4dda985facc375aecdeac00d06) just removed the umccrise pipeline config entries, investigating

**Comment by alexiswl** [comment]
Reverting commit and then re-running GitHub actions to see if this was a one-off

**Comment by alexiswl** [comment]
Reverted and triggered workflow manually

**Comment by alexiswl** [comment]
Nope, issue repeated itself.

**Comment by alexiswl** [comment]
Figured it out, seems to be two copies of umccrise-pipeline in workflow.yaml

```
yq config/workflow.yaml \
  --output-format json | \
jq \
  --raw-output 
  '
    def bow(stream):
      reduce stream as $word ({}; .[($word|tostring)] += 1);
    .workflows | 
    map(.name) | 
    bow(.[]) | 
    to_entries | 
    sort_by(-.value) | 
    from_entries
  '
```

Shows this only workflow affected

```json
{
  "umccrise-pipeline": 2,
  "optitype-pipeline": 1,
  "get-hla-regions-bed": 1,
  "dragen-germline-pipeline": 1,
  "dragen-qc-hla-pipeline": 1,
  "tso500-ctdna": 1,
  "bcl-conversion": 1,
  "dragen-somatic-pipeline": 1,
  "dragen-transcriptome-pipeline": 1,
  "dragen-alignment-pipeline": 1,
  "dragen-wgs-qc-pipeline": 1,
  "tso500-ctdna-post-processing-pipeline": 1,
  "tso500-ctdna-with-post-processing-pipeline": 1,
  "umccrise-with-dragen-germline-pipeline": 1,
  "ghif-qc": 1,
  "dragen-pon-qc": 1,
  "dragen-wts-qc-pipeline": 1,
  "tabix-workflow": 1,
  "bclconvert-with-qc-pipeline": 1,
  "bclconvert": 1,
  "bclconvert-scatter": 1,
  "validate-bclconvert-samplesheet": 1,
  "dragen-somatic-with-germline-pipeline": 1,
  "illumina-interop-qc": 1
}
```

**Comment by alexiswl** [comment]
Retriggered github actions workflow with fixed workflow.yaml

**Comment by alexiswl** [comment]
Hooray!

**Pull request merged**
