### PR TITLE
Added dragen somatic tool and pipeline

### PR DESCRIPTION
**Pull request by alexiswl**
Added dragen somatic tool and pipeline for version 4.2.4

### CODE REVIEW

**Comment by skanwal** [comment]
> Added dragen somatic tool and pipeline for version 4.0.3

4.2 I assume! Nevertheless LGTM.

**Review by skanwal — APPROVED** [review]

**Comment by skanwal** [comment]
Ughh! I had to wait for the other one to finish. Don't think sync tools can be stopped now?

**Comment by alexiswl** [comment]
> Ughh! I had to wait for the other one to finish. Don't think sync tools can be stopped now?

No, the other one was a draft so sync tools never ran.

**Comment by skanwal** [comment]
[Portal Release - Ocicat: Switch to DRAGEN 4.x](https://trello.com/c/ivLCfCrv/1510-portal-release-ocicat-switch-to-dragen-4x)

**Pull request merged**
