### PR TITLE
Upgrade dragen workflows to use latest versions of multiqc (and multiqc-interop)

### PR DESCRIPTION
**Pull request by alexiswl**
## Changes summary

Pipelines using dragen 3.9.3 or above or bclconvert 3.7.5 or above have been upgraded to use the multiqc 1.14.0 tool instead.  

Workflows that used a 'requirements override' within a workflow step to override the docker container have had this component removed.  

Multiqc interop for bclconvert has also been upgraded to 1.14.0 with interop version also upgraded to 1.2.0

## TODO

- [x] Wait for #202 
- [x] Wait for #185
- [x] Wait for #230 
- [x] Wait for #231
- [x] Wait for #242 
- [x] Wait for #236 
- [x] Compare outputs of multiqc versions for validation samples.

### CODE REVIEW

**Comment by alexiswl** [comment]
Having a small hiccup creating the workflow-submission template https://github.com/umccr/cwl-ica-cli/issues/116

**Comment by skanwal** [comment]
Also, we are still left with comparison of outputs.

**Comment by alexiswl** [comment]
>  Also, we are still left with comparison of outputs.

Yep, making the workflow templates first to then add in multiqc v1.14 in the overrides section, will then have something to compare in terms of outputs.  From running cwltool locally, I'm confident that we're good to go, but want to run it across all types of validation samples first to make sure.

**Comment by alexiswl** [comment]
## Comparisons

### Transcriptome

Compared  "wfr.485aaf32336540ee839a929473708fff" to "wfr.c81618e523ab4f5599d9ca2304475e7a"

Qualimap segment missing from original.  

GC Content also added in General Stats

[transcriptome_multiqc.zip](https://github.com/umccr/cwl-ica/files/10514317/transcriptome_multiqc.zip)

**Comment by alexiswl** [comment]
### Somatic

Compared  "wfr.25f2c89ce8954d038fdbf268d7cc70c9" (old) to "wfr.7994e0cc70584f8b816ee6260c19e06c" (new)

* GC Content % added in General Stats

* >= 20X Coverage metric in General Stats has been removed

* Contamination value removed since NA in General Stats

**Comment by alexiswl** [comment]
## Alignment

Compared "wfr.49f11128fa464351819b338532685678" (old) to "wfr.f48d8b47e4bc4a2fb37da891e6c48a54" (new)

* GC Content % added in General Stats

* \>= 20X Coverage metric in General Stats has been removed

* Contamination value removed since NA in General Stats

[wgs_alignment_multiqc.zip](https://github.com/umccr/cwl-ica/files/10514418/wgs_alignment_multiqc.zip)

**Comment by alexiswl** [comment]
## CTTSO

No old multiqc to compare to, new workflow is "wfr.96641cb36a034cf3a683ca97c6483373"

Is essentially an alignment report since multiqc takes in input from align-collapse-fusion-caller step.  

[cttso_multiqc.zip](https://github.com/umccr/cwl-ica/files/10514432/cttso_multiqc.zip)

**Comment by alexiswl** [comment]
## BCLConvert  

Compared "wfr.8ac723c7b5d34a07a0d0c38352f71b86" (old) to "wfr.e4da73b8be9a4e6eb59c456ae2d78728" (new)

* Merged interop qc and bclconvert into one multiqc file
* Dragen report also added into new report (if FPGA instance is used)
* New interop version appears to use Mb over Gb for yields which is peculiar.

**Comment by ohofmann** [comment]
Looking at the somatic comparisons - did you just re-run MultiQC or the whole pipeline? If the former I'm confused why unmapped reads doubled in the new version (and coverage dropped by 3x); mapping metrics is missing the 'Raw Depth' entry.

Overall good to go though!

**Comment by alexiswl** [comment]
> Looking at the somatic comparisons - did you just re-run MultiQC or the whole pipeline? If the former I'm confused why unmapped reads doubled in the new version (and coverage dropped by 3x); mapping metrics is missing the 'Raw Depth' entry.

Not quite comparing apples with apples on this one. 

New version uses dragen 4.0.3 but with the same reference as the old run so that could account for the changes, this was moreso testing that multiqc 1.14 was compatbile with dragen 4.0.3 rather than comparing the changes between dragen 3.9.3 and dragen 4.0.3

**Comment by skanwal** [comment]
Reviewed Dragen-transcriptome multiQC reports. Both look comparable. The only difference I have noted is in one of the plots from Dragen-FastQC outputs. Per-Position Quality Score Ranges (The range of quality value across each base position in each sample or read) in old one is missing from new one. Probably Dragen-v4 no longer produces this output which makes sense, as I don't think the plot is useful or adding anything to existing information.

**Review by skanwal — APPROVED** [review]
LGTM.

**Comment by alexiswl** [comment]
>  (The range of quality value across each base position in each sample or read) in old one is missing from new one

Looks like it's still there - just denoted as 1/2 rather than <sample_name>_read1 or <sample_name>_read2

image

**Pull request merged**
