### PR TITLE
Added umccrise version 2.0.1

### PR DESCRIPTION
**Pull request by alexiswl**
- [x] Waiting on `wfr.12fee238e9324d8a8726c72d3c97d207` to complete

### CODE REVIEW

**Comment by skanwal** [comment]
@alexiswl - can you provide quick summary/motivation for the update?
trying to confirm if this is to sync with umccrise docker version update or there other changes in the definiton as well?

**Comment by alexiswl** [comment]
Very minimal changes, merely a change to the dockerfile and using umccrise 2.0.1

```
$ diff <(cwltool --pack workflows/umccrise-with-dragen-germline-pipeline/2.0.1--3.9.3/umccrise-with-dragen-germline-pipeline__2.0.1--3.9.3.cwl 2>/dev/null) <(cwltool --pack workflows/umccrise-with-dragen-germline-pipeline/2.0.0--3.9.3/umccrise-with-dragen-germline-pipeline__2.0.0--3.9.3.cwl 2>/dev/null)
1174,1176c1174,1176
<             "id": "#umccrise__2.0.1--0.cwl",
<             "label": "umccrise v(2.0.1--0)",
<             "doc": "Documentation for umccrise v2.0.1--0\n",
---
>             "id": "#umccrise__2.0.0--0.cwl",
>             "label": "umccrise v(2.0.0--0)",
>             "doc": "Documentation for umccrise v2.0.0--0\n",
1179c1179
<                     "dockerPull": "843407916570.dkr.ecr.ap-southeast-2.amazonaws.com/umccrise:2.0.1-7f08dc4bf8",
---
>                     "dockerPull": "843407916570.dkr.ecr.ap-southeast-2.amazonaws.com/umccrise:2.0.0-130ef3be09",
1246c1246
<                     "id": "#umccrise__2.0.1--0.cwl/dragen_germline_directory"
---
>                     "id": "#umccrise__2.0.0--0.cwl/dragen_germline_directory"
1255c1255
<                     "id": "#umccrise__2.0.1--0.cwl/dragen_normal_id"
---
>                     "id": "#umccrise__2.0.0--0.cwl/dragen_normal_id"
1265c1265
<                     "id": "#umccrise__2.0.1--0.cwl/dragen_somatic_directory"
---
>                     "id": "#umccrise__2.0.0--0.cwl/dragen_somatic_directory"
1274c1274
<                     "id": "#umccrise__2.0.1--0.cwl/dragen_tumor_id"
---
>                     "id": "#umccrise__2.0.0--0.cwl/dragen_tumor_id"
1284c1284
<                     "id": "#umccrise__2.0.1--0.cwl/genomes_tar"
---
>                     "id": "#umccrise__2.0.0--0.cwl/genomes_tar"
1290c1290
<                     "id": "#umccrise__2.0.1--0.cwl/output_directory_name"
---
>                     "id": "#umccrise__2.0.0--0.cwl/output_directory_name"
1299c1299
<                     "id": "#umccrise__2.0.1--0.cwl/subject_identifier"
---
>                     "id": "#umccrise__2.0.0--0.cwl/subject_identifier"
1308c1308
<                     "id": "#umccrise__2.0.1--0.cwl/threads"
---
>                     "id": "#umccrise__2.0.0--0.cwl/threads"
1319c1319
<                     "id": "#umccrise__2.0.1--0.cwl/output_directory"
---
>                     "id": "#umccrise__2.0.0--0.cwl/output_directory"
2147c2147
<             "label": "umccrise-with-dragen-germline-pipeline v(2.0.1--3.9.3)",
---
>             "label": "umccrise-with-dragen-germline-pipeline v(2.0.0--3.9.3)",
2341c2341
<                     "run": "#umccrise__2.0.1--0.cwl",
---
>                     "run": "#umccrise__2.0.0--0.cwl",
```

**Comment by skanwal** [comment]
Easy, LGTM!

**Review by skanwal — APPROVED** [review]

**Comment by scwatts** [comment]
The `wfr.12fee238e9324d8a8726c72d3c97d207` workflow finished successfully - reports look okay.

**Review by scwatts — APPROVED** [review]

**Pull request merged**
