### PR TITLE
Added new build reference tarball for v2 (v8.2) references

### PR DESCRIPTION
**Pull request by alexiswl**
Ran the workflow wfl.01656410e5f949b194ae7e629568f0dd/4.0.3 in the development project context

**Run ID**: wfr.c66c70bca35742e381e06840b912f187

**Input JSON**:
```json
{
  "output_stem": "hg38-alt-masked-cnv-hla-rna-8-r2.0-1",
  "reference_bin": {
    "class": "File",
    "location": "https://webdata.illumina.com/downloads/software/dragen/hg38%2Balt_masked%2Bcnv%2Bhla%2Brna-8-r2.0-1.run"
  }
}
```

**Workflow Run information below**

<details>
<summary>Details</summary>

```json
{
  "acl": [
    "cid:dc8e6ba9-b744-437b-b070-4cf014694b3d",
    "tid:YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ"
  ],
  "createdBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
  "createdByClientId": "iap-aps2",
  "engineParameters": "{\"workDirectory\":\"gds://wfr.c66c70bca35742e381e06840b912f187/dragen-build-reference-tarball-4.0.3-v2\",\"outputDirectory\":\"gds://development/reference-data/dragen_hash_tables/v8-r2/\",\"tmpOutputDirectory\":\"gds://wfr.c66c70bca35742e381e06840b912f187/dragen-build-reference-tarball-4.0.3-v2/steps\",\"logDirectory\":\"gds://wfr.c66c70bca35742e381e06840b912f187/dragen-build-reference-tarball-4.0.3-v2/logs\",\"maxScatter\":32,\"outputSetting\":\"move\",\"copyOutputInstanceType\":\"StandardHiCpu\",\"copyOutputInstanceSize\":\"Medium\",\"defaultInputMode\":\"'Download'\",\"inputModeOverrides\":{},\"tesUseInputManifest\":\"'auto'\",\"cwltool\":\"3.0.20201203173111\",\"engine\":\"1.20.0-202201191609-develop\"}",
  "href": "https://aps2.platform.illumina.com/v1/workflows/runs/wfr.c66c70bca35742e381e06840b912f187",
  "id": "wfr.c66c70bca35742e381e06840b912f187",
  "input": "{\"output_stem\":\"hg38-alt-masked-cnv-hla-rna-8-r2.0-1\",\"reference_bin\":{\"class\":\"File\",\"location\":\"https://webdata.illumina.com/downloads/software/dragen/hg38%2Balt_masked%2Bcnv%2Bhla%2Brna-8-r2.0-1.run\"}}",
  "modifiedBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
  "name": "dragen-build-reference-tarball-4.0.3-v2",
  "output": "{\"output_dir_gds_folder_id\":null,\"output_dir_gds_session_id\":null,\"output_reference_tarball\":{\"basename\":\"hg38-alt-masked-cnv-hla-rna-8-r2.0-1.tar.gz\",\"class\":\"File\",\"http://commonwl.org/cwltool#generation\":0,\"location\":\"gds://development/reference-data/dragen_hash_tables/v8-r2/hg38-alt-masked-cnv-hla-rna-8-r2.0-1.tar.gz\",\"nameext\":\".gz\",\"nameroot\":\"hg38-alt-masked-cnv-hla-rna-8-r2.0-1.tar\",\"size\":10751887360}}",
  "status": "Succeeded",
  "tenantId": "YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ",
  "timeCreated": "2022-10-27T04:30:35.768Z",
  "timeModified": "2022-10-27T05:07:05.501Z",
  "timeStarted": "2022-10-27T04:30:37.800Z",
  "timeStopped": "2022-10-27T05:07:04.249Z",
  "urn": "urn:ilmn:iap:aps2:YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ:workflowrun:wfr.c66c70bca35742e381e06840b912f187#dragen-build-reference-tarball-4.0.3-v2",
  "workflowVersion": {
    "acl": [
      "tid:YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ",
      "cid:0df0356d-3637-48a5-80d1-a924642a6556",
      "cid:dc8e6ba9-b744-437b-b070-4cf014694b3d",
      "cid:c9173925-a838-4394-9fc6-61cb93c252a1"
    ],
    "createdBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
    "createdByClientId": "iap-aps2",
    "href": "https://aps2.platform.illumina.com/v1/workflows/wfl.01656410e5f949b194ae7e629568f0dd/versions/4.0.3",
    "id": "wfv.ff687f572d7542188ab74c9e32890d80",
    "language": {
      "name": "CWL",
      "version": "v1.1"
    },
    "modifiedBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
    "status": "Draft",
    "tenantId": "YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ",
    "timeCreated": "2022-10-27T03:58:15.683Z",
    "timeModified": "2022-10-27T04:30:35.768Z",
    "urn": "urn:ilmn:iap:aps2:YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ:workflowversion:wfv.ff687f572d7542188ab74c9e32890d80#4.0.3",
    "version": "4.0.3"
  }
}
```

</details>

Which created this file `gds://development/reference-data/dragen_hash_tables/v8-r2/hg38-alt-masked-cnv-hla-rna-8-r2.0-1.tar.gz`

Streaming the output file with the following command -

```bash
gds-view \
  --gds-path gds://development/reference-data/dragen_hash_tables/v8-r2/hg38-alt-masked-cnv-hla-rna-8-r2.0-1.tar.gz \
  --to-stdout | \
tar -tf -
```

produces the following contents

```
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/hash_table.cfg
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/hash_table.cfg.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/hash_table.cmp
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/hash_table_stats.txt
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/ref_index.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/reference.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/repeat_mask.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_hla/str_table.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/hash_table.cfg
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/hash_table.cfg.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/hash_table.cmp
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/hash_table_stats.txt
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/mask.bed
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/ref_index.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/reference.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/repeat_mask.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/anchored_rna/str_table.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/hash_table.cfg
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/hash_table.cfg.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/hash_table.cmp
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/hash_table_stats.txt
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/info.json
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/kmer_cnv.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/mask.bed
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/md5sum
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/ref_index.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/reference.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/repeat_mask.bin
hg38-alt-masked-cnv-hla-rna-8-r2.0-1/str_table.bin
```

### CODE REVIEW

**Comment by alexiswl** [comment]
Allows analysis discovery for #147

**Comment by alexiswl** [comment]
Referencing https://github.com/umccr-illumina/dragen/issues/50 to justify why we set the output-stem as "hg38-alt-masked-cnv-hla-rna-8-r2.0-1".

**Review by skanwal — APPROVED** [review]
Thanks, LGTM.

**Comment by alexiswl** [comment]
Waiting for #175

**Pull request merged**
