### PR TITLE
Updated arriba 2.3.0 and arriba drawing 2.3.0 hints

### PR DESCRIPTION
**Pull request by alexiswl**
## Changes

* Dockerpull moved to public aws biocontainers
* Use an appropriate instance size (4 CPU and 14 GB)

## TODO

- [x] #230 
- [x] #231 
- [x] #241

### CODE REVIEW

**Review by skanwal — COMMENTED** [review]
@alexiswl - this is only updating the tool definitions on GH but not ICA?

**Comment by alexiswl** [comment]
That's fine, it will auto-sync with dev and make a new workflow version in development on PR approval

**Comment by skanwal** [comment]
@alexiswl - okay then are you happy for this to be updated to "ready for review"?

**Review by skanwal — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
