### PR TITLE
Initialised a test of the icav2 configuration yaml

### PR DESCRIPTION
**Pull request by alexiswl**
Commands run to get this configuration:

## Add tenants
```
cwl-ica icav2-add-tenant --tenant-name "umccr-test"
```

## Add projects
```
cwl-ica icav2-add-project --tenant-name "umccr-test" --project-id "eb511e09-1b6a-4ebd-9da4-bbdecbfb934d" --project-name "umccr-test-byob-1"
cwl-ica icav2-add-project --tenant-name "umccr-test" --project-id "e22b9fcb-33ee-4dc9-9015-f1034dfd6a85" --project-name "umccr-test-byob-2"
cwl-ica icav2-add-project --tenant-name "umccr-test" --project-id "2bafbf01-dd86-4916-a097-8110b512e788" --project-name "pipelines-test"
cwl-ica icav2-add-project --tenant-name "umccr-test" --project-id "74f24a77-e639-45d9-970e-79e962516960" --project-name "staging-test"
cwl-ica icav2-add-project --tenant-name "umccr-test" --project-id "6c7b3d61-15df-45e7-9b9b-2996544e4866" --project-name "production-test"
```

## Add datasets
```
cwl-ica icav2-add-dataset --tenant-name umccr-test --input-yaml reference_dataset.yaml

cwl-ica icav2-add-dataset --tenant-name umccr-test --input-yaml
```

## Add bunches
```
cwl-ica icav2-add-bunch --input-yaml staging_bunch.yaml
cwl-ica icav2-add-bunch --input-yaml prod_bunch.yaml
```

### Dataset files

> reference_dataset.yaml

```yaml
dataset_name: dragen_hash_table_v9_r3_alt_masked_cnv_hla_rna
dataset_description: |
  A tarred version of the v9 r3 hash table for dragen 4.2.4
  This reference is a custom reference by UMCCR. It was built using the following parameters with the dragen version 4.2.4
  /opt/edico/bin/dragen \
  --build-hash-table true \
  --enable-cnv true \
  --ht-build-hla-hashtable true \
  --ht-build-rna-hashtable true \
  --ht-mask-bed /opt/edico/fasta_mask/hg38_alt_mask.bed \
  --ht-reference /data/cwl-stage-dir/stgfde7c711-e25f-42ce-b700-bbdaf23bcd2c/hg38.fa

  Where hg38.fa was downloaded from s3.amazonaws.com/stratus-documentation-us-east-1-public/dragen/reference/Homo_sapiens/hg38.fa
data:
  - icav2://umccr-test-byob-2/reference_data/dragen_hash_tables/v9-r3/hg38-alt_masked-cnv-hla-rna/hg38-alt_masked.cnv.hla.rna-9-r3.0-1.tar.gz
```

> validation_cups_pair8_dataset.yaml

```yaml
dataset_name: wgs_validation_fastq__cups_pair_8
dataset_description: |
  Fastq data from SBJ03864 (Tumor PRJ180660, Normal PRJ180661) 

  The run name for both PRJ180660 and PRJ180661 is 181211_A00130_0084_BHFTGGDSXX.

  More information on this sample can be found at https://github.com/umccr/validation_data.
data:
  - icav2://umccr-test-byob-1/validation_data/WGS/CUP-Pairs8/fastq/PRJ180661_8_DNA008678_Blood_R1.fastq.gz
  - icav2://umccr-test-byob-1/validation_data/WGS/CUP-Pairs8/fastq/PRJ180661_8_DNA008678_Blood_R2.fastq.gz
  - icav2://umccr-test-byob-1/validation_data/WGS/CUP-Pairs8/fastq/PRJ180660_8_DNA009529_FFPE_R1.fastq.gz
  - icav2://umccr-test-byob-1/validation_data/WGS/CUP-Pairs8/fastq/PRJ180660_8_DNA009529_FFPE_R2.fastq.gz
```

### Bunch files

> staging_bunch.yaml

```
tenant_name: umccr-test
bunch_name: dragen_somatic_with_germline_pipeline_validation__4_2_4
bunch_description: |
  Contains the UMCCR dragen-somatic-with-germline pipeline, validation data and the appropriate reference data for dragen version 4.2.4
  
  The reference data is the dragen hash table for hg38.
  Version for v9-r3 with alt-masked, cnv, hla, rna enabled features

bunch_version: v9_r3__w_cups_pair_8
bunch_version_description: |
  v9r3 is the hash table build.
  
  The validation data the cups pair 8

workflow_path: workflows/dragen-somatic-with-germline-pipeline/4.2.4/dragen-somatic-with-germline-pipeline__4.2.4.cwl
pipeline_project_name: pipelines-test
datasets:
 - dragen_hash_table_v9_r3_alt_masked_cnv_hla_rna
 - wgs_validation_fastq__cups_pair_8
projects: 
 - staging-test
categories:
 - dragen
 - somatic
 - validation
```

> prod_bunch.yaml

```yaml
tenant_name: umccr-test
bunch_name: dragen_somatic_with_germline_pipeline_production__4_2_4
bunch_description: |
  Contains the UMCCR dragen-somatic-with-germline pipeline and the appropriate reference data for dragen version 4.2.4
  
  The reference data is the dragen hash table for hg38.
  Version for v9-r3 with alt-masked, cnv, hla, rna enabled features

bunch_version: v9_r3
bunch_version_description: |
  v9r3 is the hash table build.

workflow_path: workflows/dragen-somatic-with-germline-pipeline/4.2.4/dragen-somatic-with-germline-pipeline__4.2.4.cwl
pipeline_project_name: pipelines-test
datasets:
 - dragen_hash_table_v9_r3_alt_masked_cnv_hla_rna
projects:
  - staging-test
  - production-test

categories:
 - dragen
 - somatic
 - production

```

### CODE REVIEW

**Comment by alexiswl** [comment]
## TODO

- [ ] Link to an cwl-ica-cli release
- [ ] Demonstrate bundle generation via tag

**Comment by alexiswl** [comment]
Resolves https://github.com/umccr/cwl-ica/issues/353

**Comment by alexiswl** [comment]
This is the release generated locally by these 'bunches':  https://github.com/umccr/cwl-ica/releases/tag/dragen-somatic-with-germline-pipeline%2F4.2.4__12345

**Comment by alexiswl** [comment]
- [ ] Redo this entire process with the project setup as follows

icav2-umccr-test drawio

**Review by skanwal — APPROVED** [review]

**Pull request merged**
