### PR TITLE
Mapping ResourceRequirement using JS

### PR DESCRIPTION
**Pull request by skanwal**
The tool definition to mainly investigate and discuss https://github.com/umccr-illumina/ica_v2/issues/103 with Illumina

### CODE REVIEW

**Comment by alexiswl** [comment]
Sweet, looks good, will wait for the sync on https://github.com/umccr/cwl-ica/pull/163 to finish first and then approve

**Comment by alexiswl** [comment]
## TODO 
- [ ] Wait for #163 and then update with main branch

**Review by alexiswl — APPROVED** [review]

**Comment by skanwal** [comment]
@alexiswl - FYI, I have merged main into this branch.

**Comment by alexiswl** [comment]
> @alexiswl - FYI, I have merged main into this branch.

Which commit are you referring to here?

**Comment by alexiswl** [comment]
## TODO 

- [ ] Wait for https://github.com/umccr/cwl-ica/pull/167

**Comment by skanwal** [comment]
> Which commit are you referring to here?

Ah, I see you had already pulled main, and repeating that locally only pulled in those changes https://github.com/umccr/cwl-ica/pull/164/commits/f3b1b650af3f83030172fce497abfb12f8b4daaa

**Comment by alexiswl** [comment]
Re-running GH actions now

**Pull request merged**
