### PR TITLE
Add STAR tool

### PR DESCRIPTION
**Pull request by skanwal**
Motivation was the investigation underneath https://github.com/suhrig/arriba/issues/179.

However, ended up running STAR on gadi as we don't have indices on ICA. Thought this tool still might be useful for similar or other work.

## TODO 

- [x] Wait for #220 to be resolved
- [x] Wait for #205 
- [x] Wait for #225

### CODE REVIEW

**Comment by skanwal** [comment]
@alexiswl - dependencies for this PR have been completed, I have merged main into it and marked it as ready for review.

**Comment by alexiswl** [comment]
Need to wait for the sync to occur that should have happened in #205 (new PR for the update-ilmn-tes-namespace-to-https-url pending)

**Comment by alexiswl** [comment]
Does this mean we can close https://github.com/umccr/cwl-ica-cli/issues/107? 

> as we don't have indices on ICA

Is it worth trying to build indices on ICA? Would this tool be more useful if we had an index tool as well?

**Comment by skanwal** [comment]
> Is it worth trying to build indices on ICA? Would this tool be more useful if we had an index tool as well?

We have star indices on gadi. We just need to copy these over. 

> Are you happy with the version naming? Does this mean we can close https://github.com/umccr/cwl-ica-cli/issues/107?

For current CLI, I am okay with this version but would like to keep the ticket open as a feature request for future.

**Comment by alexiswl** [comment]
> For current CLI, I am okay with this version but would like to keep the ticket open as a feature request for future.

Will follow this up in the cli issue.  

> We have star indices on gadi. We just need to copy these over.

Understood, would it be beneficial to others though?

**Review by alexiswl — APPROVED** [review]

**Comment by skanwal** [comment]
> Understood, would it be beneficial to others though?

I'd think so. Most probably I'll be the one revisiting/needing it again. So will add it to my to-do.

**Pull request merged**
