### PR TITLE
Added in umccrise version 2.1.0

### PR DESCRIPTION
**Pull request by alexiswl**

### CODE REVIEW

**Comment by alexiswl** [comment]
Have kicked off the sync gh workflow already so no immediate rush

**Review by pdiakumis — APPROVED** [review]
Thanks for this too Alexis! So... the 2.1.0 isn't really needed, right? I mean, there isn't even a working image for it.

**Comment by skanwal** [comment]
> I mean, there isn't even a working image for it.

I'd suggest getting rid of 2.1.0 if that's the case.

**Review by skanwal — CHANGES_REQUESTED** [review]
Under discussion to remove v2.1.0 if it isn't used/available.

**Comment by alexiswl** [comment]
I left it in since we can't delete workflow versions on ICA, this way we at least have a trace of how it was generated.

**Comment by alexiswl** [comment]
@skanwal okay to merge? Since we've done the sync tool already, pulling out umccrise 2.1.0 of catalogues and configurations won't be trivial

**Comment by skanwal** [comment]
@alexiswl - yes, lets skip this and move on with updates for next portal release.

**Pull request merged**
