### PR TITLE
Tso500 updates

### PR DESCRIPTION
**Pull request by alexiswl**
## Additions

* Added local cwltool compatible (and v2 compatible) version of the custom-create-directory (version 2.0.1)

## Updates
* Simplified tso500 cromwell workflows to have their shell scripts in the listing rather than in a function call.
* Migrated tso500 post-processing and coupling workflow to use the new version of the custom-create-directory command.

### CODE REVIEW

**Comment by alexiswl** [comment]
Confirming successful run of `wfr.799cb55df70f43d9bd49b1203694ffe8` before merging

**Comment by alexiswl** [comment]
Watching `wfr.d4cc3c36f3cd4965b1a8fc250c6a4736` under the collab-illumina-dev project for successful result and then this workflow is good to go

**Comment by alexiswl** [comment]
Might also use this as an opportunity to update the fastq mounts for the demux and analysis workflows that mount the fastq files in the fastq-list-rows

**Comment by skanwal** [comment]
Once TSO workflow is successfulI, I suggest we freeze our production workflows for v1.
Then get these ported to v2 for feature parity. Once, we are happy that these analysis workflows also work on v2, we can start making changes/improvements. 
We can keep testing/updating workflows in branches but IMO should freeze the workflows on main branch, unless updates are necessary!

**Comment by alexiswl** [comment]
Also updated containers to official bash image containers

**Comment by skanwal** [comment]
Nice - approving this since we have successful runs in both dev and collab-illumina-dev projects.

**Review by skanwal — APPROVED** [review]
Nice - approving this since we have successful runs in both dev and collab-illumina-dev projects.

**Pull request merged**
