### PR TITLE
added CNV pipeline option

### PR DESCRIPTION
**Pull request by skanwal**
Updated tool definition in `development_workflows`

### CODE REVIEW

**Comment by alexiswl** [comment]
Looks good! Did you want to put this in the workflow as well?

**Comment by alexiswl** [comment]
Also will merge in the main branch into this one once I've completed the following:
- [ ] https://github.com/umccr/cwl-ica/projects/5#card-65697089
- [ ] https://github.com/umccr/cwl-ica/projects/5#card-68411341

Then I'll approve, it should mean less files are changed

**Comment by skanwal** [comment]
Okay - updated the pipeline as well - under `development_workflows`

**Review by alexiswl — APPROVED** [review]

**Comment by alexiswl** [comment]
@skanwal looks like dd35f71 missed the actual CWL workflow file itself. Would you mind uploading that one too?

**Comment by skanwal** [comment]
I moved `type` for `enable_cnv` after the `doc`. Also, updated and pushed the workflow.

**Comment by alexiswl** [comment]
Yep all approved on my end! Ready for merge

**Pull request merged**
