### PR TITLE
Upgraded dragen workflows to use multiqc v1.13dev

### PR DESCRIPTION
**Pull request by alexiswl**
# To do list:
- [x] Merge #80 
- [x] Merge #82 
- [x] Merge main into this branch
- [x] Update project.yaml, workflow.yaml for each workflow changes
- [x] Run tests against each workflow and ensure multiqc output looks good.

### CODE REVIEW

**Comment by alexiswl** [comment]
Testing the following multiqc outputs:

### WGS QC Pipeline test

**Workflow ID**
`wfr.ee6d043bda174080b79b32a515715feb`

**Subject ID**
SBJ00910

### TN Multiqc 1.13 Test

**Workflow ID**
* wfr.3948f397e6c047a59cabc1a6d9d0f16f

**Subject ID**
SBJ00915

### TO Multiqc 1.13 Test

This workflow is identical to above but with the 'fastq_list_rows' attribute removed

**Workflow ID**
* wfr.178ac135dd1f418ca17d58cdf8a371bc

**SubjectID**
SBJ00915

**Comment by alexiswl** [comment]
Now ready to review

**Comment by skanwal** [comment]
@alexiswl - can you also test Dragen-transcrpitome workflow again the new tool definition (v1.12)?

**Comment by alexiswl** [comment]
Running under `wfr.9bb5c7d51bfd4f39bba2e01ff4f35448`

**Comment by alexiswl** [comment]
Yep workflow succeeded and multiqc output is all good

**Review by skanwal — APPROVED** [review]
LGTM!

**Pull request merged**
