### PR TITLE
Converted http to https for ilmn-tes namespace

### LINKED ISSUE #204: Updated resources using new ilmn-tes syntax not working
The updated syntax in PR https://github.com/umccr/cwl-ica/pull/200 doesn't work for the tools I have tested.

One of the examples is RNAsum workflow run in dev wfr.898459586832470496d282cde75bb90f. The dragen WTS workflow also fails with hardware error as it specifically needs FPGA wfr.7d1a060c0be841f2b6b8b6977ae6af2f. 

Checking with Pratik on to see if this is the correct syntax https://github.com/umccr-illumina/cwl-iap/issues/189#issuecomment-1369404594.

### PR DESCRIPTION
**Pull request by alexiswl**
Resolves #204 

Discussed further in https://github.com/umccr-illumina/cwl-iap/issues/189

## TODO

- [x] #206 
- [x] https://github.com/umccr/cwl-ica/issues/208
- [x] #220 
- [x] #225

### CODE REVIEW

**Review by skanwal — APPROVED** [review]
LGTM, thanks.

**Comment by alexiswl** [comment]
@skanwal re-requested review for this one after merging in #206

**Review by skanwal — APPROVED** [review]
LGTM, thanks.

**Comment by alexiswl** [comment]
Cry, this one failed since need to do the same CONDA_ENVS_PATH logic with the create catalogue script.  

This might mean a few things are out of sync since they weren't committed in the sync tools stage.  Might need a bit of manual work.

**Comment by alexiswl** [comment]
@skanwal since this PR had been pre-approved, there was no sync stage, restoring this branch and triggering the workflow manually

**Pull request merged**
