### PR TITLE
remove ilmn-tes namespace when not used

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by alexiswl** [comment]
@skanwal can discuss this in our meeting tomorrow. Looks like we can remove them from expressions but for the tool listed, we should probably just add in the ilmn-tes requirements?

**Comment by skanwal** [comment]
@alexiswl - Yes, lets discuss before making changes.

**Review by skanwal — APPROVED** [review]
Discussed and LGTM, thanks @mr-c.

**Comment by alexiswl** [comment]
Looks like the project token expired, which seems weirdly short since I only updated them a few weeks go?

**Comment by alexiswl** [comment]
Also can we fix the tool first (add in the ilmn resource requirements there) before merging

**Comment by skanwal** [comment]
> Also can we fix the tool first (add in the ilmn resource requirements there) before merging

@alexiswl - you're referring to this [tools/create-dummy-file/1.0.0/create-dummy-file__1.0.0.cwl](https://github.com/umccr/cwl-ica/pull/115/files#diff-b45353e45d17b2a204b3fc1b7c216f57277e9e2e75e75e0873fbc2d2fa12c394)?

**Comment by alexiswl** [comment]
Yep

**Comment by skanwal** [comment]
@mr-c - can you please make the suggested change https://github.com/umccr/cwl-ica/pull/115#issuecomment-1240031436?

**Comment by mr-c** [comment]
> @mr-c - can you please make the suggested change https://github.com/umccr/cwl-ica/pull/115#issuecomment-1240031436? 

Sorry, I don't understand the exact request.

**Comment by alexiswl** [comment]
> Looks like the project token expired, which seems weirdly short since I only updated them a few weeks ago?

Ah likely an issue when running the action from a fork and not having access to the secrets, so this checks out. 

> Sorry, I don't understand the exact request.

Yup no stress happy to do this on our end. Will close this PR and merge your branch into a branch on our remote first and add in the resources to that tool on that branch. Then when I do the PR the sync GH action will work too.

**Pull request closed without merging**
