### PR TITLE
Add RNA-options to WGS alignment workflow

### PR DESCRIPTION
**Pull request by skanwal**
**Changes:**

- Added RNA specific options to dragen-alignment tool definition
- Updated dragen-alignment-pipeline to use RNA specific arguments
- Updated configs

**Test:**

ICA workflow run ID is `wfr.e214f88cec5a4a4083545852a53a7f3a`. The inputs used were:

<details>
  <summary>Click to expand!</summary>

```json
{
    "name": "Dragen-WTS-QC",
    "input": {
        "reference_tar": {
            "class": "File",
            "location": "gds://development/reference-data/dragen_hash_tables/v8/hg38/altaware-cnv-anchored/hg38-v8-altaware-cnv-anchored.tar.gz"
        },
        "output_file_prefix": "MDX210318",
        "output_directory": "L2101521_dragen",
        "fastq_list_rows": [
            { 
                "rgid": "MDX210318",
                "rgsm": "MDX210318",
                "rglb": "L2101521",
                "lane": 1,
                "read_1": {
                  "class": "File",
                  "location": "gds://production/primary_data/211125_A00130_0185_AHWC2HDSX2/2022010575cdcf71/WTS_NebRNA/MDX210318_L2101521_S1_L004_R1_001.fastq.gz"
                },
                "read_2": {
                  "class": "File",
                  "location": "gds://production/primary_data/211125_A00130_0185_AHWC2HDSX2/2022010575cdcf71/WTS_NebRNA/MDX210318_L2101521_S1_L004_R2_001.fastq.gz"
                }
            }
        ],
        "enable_map_align_output": true,
        "enable_duplicate_marking": false,
        "enable_sort": true,
        "enable_rna": true,
        "enable_rrna_filter": true
    },
    "engineParameters": {
        "outputDirectory": "gds://development/temp/sehrish/dragne_wts_alignment/MDX210318",
        "workDirectory": "gds://development/temp/sehrish/dragne_wts_alignment/MDX210318_work"
    }
}
```

</details>

## TODO

- [x] #232
- [x] #236

### CODE REVIEW

**Comment by alexiswl** [comment]
Cool! Can you also update dragen alignment v4 as well?

**Comment by skanwal** [comment]
@alexiswl - updated in https://github.com/umccr/cwl-ica/pull/245/commits/db539d62243a00dc7c891f492348c6d7007290cf

**Comment by alexiswl** [comment]
@skanwal I don't think your merge from main was successful [e3558c8](https://github.com/umccr/cwl-ica/pull/245/commits/e3558c83f9d956617e40ed58a8b21b936a9174b5)

**Comment by alexiswl** [comment]
This conflict is expected since main has updated the multiqc version to 1.14 and the wts-qc-workflow branch has updated the same workflow (but adding in the rna inputs). This also means that neither branch has the correct md5sum. To avoid this conflict in future, a better option may be to rebase the workflow onto main then run the sync commands to update the project config yaml files. 

In this case I was able to merge, pick one md5sum, then re-run the sync command to get the correct md5sum.

**Review by alexiswl — APPROVED** [review]

**Pull request merged**
