### PR TITLE
Dragen WTS 4.2 pipeline

### PR DESCRIPTION
**Pull request by skanwal**
- Create dragen transcriptome 4.2 tool 
- Create dragen transcriptome 4.2 QC pipeline for multiQC reference samples
            - tested using `wfr.51ed3e9ce6f047ecbba1f4f87bccc1c8`
- Create dragen transcriptome 4.2 pipeline
            - tested using `wfr.d228c87fd926443e973cf9d57fe31e0c`

### CODE REVIEW

**Comment by alexiswl** [comment]
Great work! Did you also want to add these to the _production_workflows_ project?

**Comment by skanwal** [comment]
@alexiswl - updated in [`c86e17f` (#376)](https://github.com/umccr/cwl-ica/pull/376/commits/c86e17fae34f4b19fa35a04ef76488265194e928)

**Comment by skanwal** [comment]
[Update Dragen transcriptome pipeline to v4.2.4](https://trello.com/c/BaSWMILf/1517-update-dragen-transcriptome-pipeline-to-v424)

**Comment by alexiswl** [comment]
On hold, waiting for explanation on multiqc changes:
* rrna pct 
* qualimap coverage profile

**Comment by skanwal** [comment]
[Portal Release - Ocicat: Switch to DRAGEN 4.x](https://trello.com/c/ivLCfCrv/1510-portal-release-ocicat-switch-to-dragen-4x)

**Comment by alexiswl** [comment]
As discussed in meetring today merge in #384 into this branch and then point to new multiqc tool in WTS workflow

**Comment by skanwal** [comment]
> then point to new multiqc tool in WTS workflow

Done in [`aeba7d4` (#376)](https://github.com/umccr/cwl-ica/pull/376/commits/aeba7d4acb7257afb6552b59f6d7e11dd50d7830)

**Comment by alexiswl** [comment]
Do you want to rerun wfr.d228c87fd926443e973cf9d57fe31e0c with the new multiqc and we'll merge this in

**Comment by alexiswl** [comment]
Can you also run `cwl-ica add-workflow-to-project /path/to/dragen-transcriptome-pipeline__4.2.4.cwl --project production_workflows`, saves having to do a second PR later down the track? We've also run all of the WGS pdacs so onto the WTS now and we need a production workflow version

**Comment by skanwal** [comment]
That's done here https://github.com/umccr/cwl-ica/pull/376#issuecomment-1647028787 already?

**Comment by alexiswl** [comment]
> That's done here [#376 (comment)](https://github.com/umccr/cwl-ica/pull/376#issuecomment-1647028787) already?

Awesome! 

Can you rerun wfr.d228c87fd926443e973cf9d57fe31e0c?

**Comment by skanwal** [comment]
Running with `wfr.c8ada35671a54106bae01fa9c9bea4a5`

**Review by alexiswl — APPROVED** [review]

**Pull request merged**
