### PR TITLE
Initialise RNAsum v1.1.5

### PR DESCRIPTION
**Pull request by skanwal**
Tested on icav1 `wfr.f0bbfab8e61c4dcba9a619be30f231fb`

### CODE REVIEW

**Review by pdiakumis — APPROVED** [review]
LGTM
ss 2024-11-11 at 15 51 35

**Comment by alexiswl** [comment]
Great! Can you create a Workflow along with the CommandLineTool so that we can run it in ICAv2?

**Comment by skanwal** [comment]
@alexiswl - i have pushed the pipeline as well. Do we need to rerun GH actions?

**Comment by alexiswl** [comment]
> Do we need to rerun GH actions?

Yeah I'll add the pipeline to the catalogue as well.  

For V2 I'll add in the 'bunch' (aka pre-bundle) so we can deploy into ICAv2

**Comment by alexiswl** [comment]
Bunch added with 

```
cwl-ica icav2-add-bunch \
  --tenant-name umccr-prod \
  --bunch-name rnasum_prod__1_1_5 \
  --bunch-description "Contains the UMCCR rnasum pipeline for RNA-seq data analysis with reference data" \
  --workflow-path workflows/rnasum-pipeline/1.1.5/rnasum-pipeline__1.1.5.cwl \
  --pipeline-project-name pipelines \
  --project development \
  --project staging \
  --project production \
  --category wts \
  --category tertiary-analysis \
  --category production \
  --bunch-version 1.0.0 \
  --bunch-version-description "This version of the bunch contains the rnasum 1.0.0 reference data" \
  --dataset rnasum_1_0_0
```

**Pull request merged**
