### PR TITLE
Add umccrise v2.2 tool

### PR DESCRIPTION
**Pull request by pdiakumis**
Adding tools for v2.2.0 and v2.2.1 of umccrise. I'm not touching the workflow side of things since I believe that's being worked on a separate branch.
Keeping track of steps here:

- Step 0:

```bash
cwl-ica configure-user \
  --username "Peter Parker" \
  --email "peter.parker@marvel.org" \
  --set-as-default
```

- Step 1:
 
```
cwl-ica create-tool-from-template \
  --tool-name umccrise \
  --tool-version 2.2.0 \
  --username "Peter Parker"
```

Then edit the rest of `tools/umccrise/2.2.0--0/umccrise__2.2.0--0.cwl` according to the previous version of the tool.

- Step 2:

```
cwl-ica tool-validate \
  --tool-path "tools/umccrise/2.2.0--0/umccrise__2.2.0--0.cwl"
```

- Step 3:

```
cwl-ica tool-init \
  --tool-path "tools/umccrise/2.2.0--0/umccrise__2.2.0--0.cwl"
```

Needed to also do `chmod +x ${CONDA_PREFIX}/etc/get_api_key.sh`

### CODE REVIEW

**Comment by alexiswl** [comment]
Great stuff! I've just reran the sync, all fine on the ICA side, but we had a UTF-8 issue (see https://github.com/umccr/cwl-ica-cli/releases/tag/v1.2.1).  I've also updated the cwl-ica wiki which was pointing to the wrong releases page, latest release was https://github.com/umccr/cwl-ica-cli/releases/tag/v1.2.5

**Review by alexiswl — APPROVED** [review]

**Comment by alexiswl** [comment]
Ah did you want the tool in the production context too?

**Comment by pdiakumis** [comment]
Ah yep, I'm not sure how to do that?

**Comment by alexiswl** [comment]
Awesome, will wait for this sync to finish first.  

1. Then pull in the changes (if any) made by the sync.  
2. Run the add-tool-to-project subcommand with `production_workflows` as the `--project` parameter and the umccrise tool cwl as a the `--tool-path` parameter.  
3. This should create a new entry in project.yaml that has place holders for the actual version name. 
4. We then push the project.yaml changes back to github and re-run the workflow (you can do this manually - see the image below)


image

**Pull request merged**
