### PR TITLE
Allow read1 and read2 attributes to be of string type in fastq list row schema

### PR DESCRIPTION
**Pull request by alexiswl**
This allows read1file and read2file attributes for fastq-list-row schemas to be presigned urls rather than file objects.  

Dragen supports presigned urls in the csv for these columns.  

This means data is not mounted into the task instance prior to the task starting, allowing the task to start sooner.

Examples on ICA can be seen with

`wfr.cdfbfbe76bb54ac9852711c2e3795806` / `trn.b8655dce66294249ad130a29090fce1d`

```
ica tasks runs get trn.b8655dce66294249ad130a29090fce1d
```

### CODE REVIEW

**Comment by alexiswl** [comment]
## Task Run 

Yields

<details>

<summary>Details</summary>

```json
{
        "acl": [
                "cid:dc8e6ba9-b744-437b-b070-4cf014694b3d",
                "tid:YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ"
        ],
        "createdBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
        "execution": {
                "args": [
                        "run-dragen-script.sh",
                        "--intermediate-results-dir=/ephemeral/intermediate-results/",
                        "--enable-duplicate-marking=true",
                        "--enable-map-align-output=true",
                        "--enable-sv=true",
                        "--fastq-list=fastq_list.csv",
                        "--lic-instance-id-location=/opt/instance-identity",
                        "--output-directory=L2100751_L2100219_dragen",
                        "--output-file-prefix=PRJ210678",
                        "--ref-dir=/ephemeral/ref/hg38-v8-altaware-cnv-anchored/",
                        "--tumor-fastq-list=tumor_fastq_list.csv",
                        "--enable-variant-caller=true"
                ],
                "command": "bash",
                "environment": {
                        "inputStreamSettings": {
                                "accessPattern": "sequential",
                                "blockSizeMB": 32,
                                "cacheSizeGB": 50,
                                "prefetchBlocks": 32
                        },
                        "resources": {
                                "hardware": [],
                                "size": "medium",
                                "tier": "standard",
                                "type": "fpga"
                        },
                        "variables": {
                                "HOME": "/pePpcu",
                                "TMPDIR": "/tmp"
                        }
                },
                "image": {
                        "name": "699120554104.dkr.ecr.us-east-1.amazonaws.com/public/dragen:4.0.3"
                },
                "inputs": [
                        {
                                "mode": "Download",
                                "path": "/data/cwl-stage-dir/stgface6780-910d-4971-ac76-8b4a4edf0868/hg38-v8-altaware-cnv-anchored.tar.gz",
                                "type": "File",
                                "url": "gds://development/reference-data/dragen_hash_tables/v8/hg38/altaware-cnv-anchored/hg38-v8-altaware-cnv-anchored.tar.gz"
                        },
                        {
                                "mode": "Download",
                                "path": "/pePpcu/run-dragen-script.sh",
                                "type": "File",
                                "url": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/steps/run_dragen_somatic_step/try-1/run-dragen-script.sh"
                        },
                        {
                                "mode": "Download",
                                "path": "/pePpcu/fastq_list.csv",
                                "type": "File",
                                "url": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/steps/run_dragen_somatic_step/try-1/fastq_list.csv"
                        },
                        {
                                "mode": "Download",
                                "path": "/pePpcu/tumor_fastq_list.csv",
                                "type": "File",
                                "url": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/steps/run_dragen_somatic_step/try-1/tumor_fastq_list.csv"
                        }
                ],
                "outputs": [
                        {
                                "path": "/pePpcu",
                                "url": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/steps/run_dragen_somatic_step/try-1"
                        },
                        {
                                "path": "/var/log/tessystemlogs",
                                "url": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/logs/run_dragen_somatic_step/try-1"
                        }
                ],
                "retryLimit": 0,
                "systemFiles": {
                        "url": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/logs/run_dragen_somatic_step/try-1"
                },
                "workingDirectory": "/pePpcu"
        },
        "href": "https://aps2.platform.illumina.com/v1/tasks/runs/trn.b8655dce66294249ad130a29090fce1d",
        "id": "trn.b8655dce66294249ad130a29090fce1d",
        "logs": [
                {
                        "endTime": "2023-02-21T14:04:13.271Z",
                        "startTime": "2023-02-21T10:33:38.759Z",
                        "stderr": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/logs/run_dragen_somatic_step/try-1/task-stderr-0.log",
                        "stdout": "gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/logs/run_dragen_somatic_step/try-1/task-stdout-0.log"
                }
        ],
        "modifiedBy": "b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
        "name": "dragen-somatic__4.0.3.cwl",
        "status": "Completed",
        "statusDetails": "",
        "subTenantId": "uid:b2f0ff65-c77b-37bc-af87-68a89c2f8d27",
        "tenantId": "YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ",
        "timeCreated": "2023-02-21T10:25:30.510Z",
        "timeModified": "2023-02-21T14:04:55.094Z"
}
```


</details>

**Comment by alexiswl** [comment]
## Fastq List CSV


Where 

```shell
gds-view \
   --to-stdout
  --gds-path gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/steps/run_dragen_somatic_step/try-1/fastq_list.csv
```

Yields

<details>
<summary>Details</summary>

```
Lane,Read1File,Read2File,RGID,RGLB,RGSM
1,https://stratus-gds-aps2.s3.ap-southeast-2.amazonaws.com/11143240-789c-4320-b4e2-08d89d4636a9/primary_data/210331_A01052_0041_BHYMHFDSXY/2022010540ea2224/WGS_TsqNano/PRJ210193_L2100219_S2_L001_R1_001.fastq.gz?X-Amz-Expires=604800&response-content-disposition=filename%3D%22PRJ210193_L2100219_S2_L001_R1_001.fastq.gz%22&response-content-type=application%2Fx-gzip&x-userId=b2f0ff65-c77b-37bc-af87-68a89c2f8d27&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXX&X-Amz-Date=20230221T101920Z&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXXXXX,https://stratus-gds-aps2.s3.ap-southeast-2.amazonaws.com/11143240-789c-4320-b4e2-08d89d4636a9/primary_data/210331_A01052_0041_BHYMHFDSXY/2022010540ea2224/WGS_TsqNano/PRJ210193_L2100219_S2_L001_R2_001.fastq.gz?X-Amz-Expires=604800&response-content-disposition=filename%3D%22PRJ210193_L2100219_S2_L001_R2_001.fastq.gz%22&response-content-type=application%2Fx-gzip&x-userId=b2f0ff65-c77b-37bc-af87-68a89c2f8d27&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXX&X-Amz-Date=20230221T101943Z&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXXX,TTGCCTAG.TAAGTGGT.1.210331_A01052_0041_BHYMHFDSXY.PRJ210193_L2100219,L2100219,PRJ210193
```

</details>

**Comment by alexiswl** [comment]
## Task duration comparison

```shell
(
  # Old workflow run
  ica-get-tasks-from-workflow-history --ica-workflow-run-id wfr.811cc027c89440bca993811cdd3d7462;
  # New workflow run
  ica-get-tasks-from-workflow-history --ica-workflow-run-id wfr.cdfbfbe76bb54ac9852711c2e3795806;
) | \
jq --slurp --raw-output \
 '
   def from_millisecond_isoformat_date:
     # Convert time in format 2023-01-18T02:00:21.214869Z to epoch integer 1676988531
     split(".")[0] + "Z" | fromdate
   ;
   map(
     .["/run_dragen_somatic_step"] |
     {
       "task_id": .task_id,
       "task_duration": (
         ( .task_completion_time | from_millisecond_isoformat_date ) -
         ( .task_launch_time | from_millisecond_isoformat_date )
       )
     }
   )
 '

```


Yields

```
[
  {
    "task_id": "trn.cf881b93a18f4e89bf9e7fcbe17f9b33",
    "task_duration": 12852
  },
  {
    "task_id": "trn.b8655dce66294249ad130a29090fce1d",
    "task_duration": 13401
  }
]
```

So the task runs around 10 minutes slower compared to mounting prior. 

What about the workflow lengths themselves?  

```
[
  {
    "workflow_id": "wfr.811cc027c89440bca993811cdd3d7462",
    "workflow_duration": 15734
  },
  {
    "workflow_id": "wfr.cdfbfbe76bb54ac9852711c2e3795806",
    "workflow_duration": 16508
  }
]
```

Hmm, so another 10 minutes with this method.  

In conclusion, it seems mounting files prior to running dragen is more efficient than embedding the presigned url inside the fastq list csv. This is not surprising. It would be interesting to note if this is faster than the ICAv2 method of downloading locally then launching the FPGA task.

**Comment by alexiswl** [comment]
## Comparing Dragen Time Metrics

### Old task run (trn.cf881b93a18f4e89bf9e7fcbe17f9b33)

```
RUN TIME,,Time loading reference,00:01:28.403,88.40
RUN TIME,,Time aligning reads,00:28:32.729,1712.73
RUN TIME,,Time duplicate marking,00:01:24.085,84.09
RUN TIME,,Time sorting and marking duplicates,01:41:43.001,6103.00
RUN TIME,,Time DRAGStr calibration,00:00:16.364,16.36
RUN TIME,,Time saving map/align output,01:41:45.465,6105.47
RUN TIME,,Time variant calling,01:41:45.043,6105.04
RUN TIME,,Time partitioning,00:28:31.195,1711.20
RUN TIME,,Time structural variant calling,00:41:44.379,2504.38
RUN TIME,,Total runtime,02:56:21.491,10581.49
```

### New task run (trn.b8655dce66294249ad130a29090fce1d)

```
RUN TIME,,Time loading reference,00:01:24.928,84.93
RUN TIME,,Time aligning reads,00:31:48.489,1908.49
RUN TIME,,Time duplicate marking,00:01:22.489,82.49
RUN TIME,,Time sorting and marking duplicates,01:50:07.891,6607.89
RUN TIME,,Time DRAGStr calibration,00:00:16.144,16.14
RUN TIME,,Time saving map/align output,01:54:34.061,6874.06
RUN TIME,,Time variant calling,01:54:33.666,6873.67
RUN TIME,,Time partitioning,00:31:46.389,1906.39
RUN TIME,,Time structural variant calling,00:41:50.951,2510.95
RUN TIME,,Total runtime,03:12:27.186,11547.19
```

**Comment by skanwal** [comment]
@alexiswl, that's useful. To clarify, we'll only have read2 as option input? 
This actually also bodes well with the use-case of single ended read data. For context, I had some external data to process through Dragen WTS workflow that was single ended.

**Comment by alexiswl** [comment]
> To clarify, we'll only have read2 as option input?

Yep, read2 has always been optional, but we've almost always had paired end data so have always specified it.

**Comment by alexiswl** [comment]
@skanwal this isn't so much about inputs being optional but read1file and read2file having the capacity to be a string (presigned url), rather than a file

**Comment by alexiswl** [comment]
Only one-vs-one task / workflow comparison so hard to know if the extra task length may have been redeemed by the task starting sooner.  

We can look at the download init logs for comparison

### trn.cf881b93a18f4e89bf9e7fcbe17f9b33 (old)

**Time Created**

```
ica tasks runs get trn.cf881b93a18f4e89bf9e7fcbe17f9b33 -o json | jq '.timeCreated'
```

Yields

```
"2023-01-18T02:00:21.107Z"
```

**Download Logs**

```
gds-view \
  --gds-path gds://development/temp/alexis/multiqc-1.14-testing/work/20230118_125659/logs/run_dragen_somatic_step/try-1/download-init-stdout-0.log \
  --to-stdout
```

Yields

```
-rw-r--r--    1 root     22052    35917780938 Jan 18 02:13 /mount/mount/data/cwl-stage-dir/stg337979c6-f971-4779-91aa-234c9a029c94/PRJ210193_L2100219_S2_L001_R1_001.fastq.gz
-rw-r--r--    1 root     22052    98730965482 Jan 18 02:16 /mount/mount/data/cwl-stage-dir/stgc01a8b4c-63b4-4895-b882-fb68eb60be61/PRJ210678_L2100751_S9_L004_R1_001.fastq.gz
-rw-r--r--    1 root     22052    107084730250 Jan 18 02:17 /mount/mount/data/cwl-stage-dir/stg893438ce-92fd-4302-b25e-bc0b60dbcead/PRJ210678_L2100751_S9_L004_R2_001.fastq.gz
-rw-r--r--    1 root     22052          336 Jan 18 02:09 /mount/mount/QFWQQh/fastq_list.csv
-rw-r--r--    1 root     22052          336 Jan 18 02:09 /mount/mount/QFWQQh/tumor_fastq_list.csv
-rw-r--r--    1 root     22052    7664401964 Jan 18 02:10 /mount/mount/data/cwl-stage-dir/stg6c25d0d8-94bc-4c21-8b5c-1f138de7261a/hg38-v8-altaware-cnv-anchored.tar.gz
-rw-r--r--    1 root     22052    37922930102 Jan 18 02:14 /mount/mount/data/cwl-stage-dir/stgd09be1a5-16c4-498b-8a65-1e4d18fc9a87/PRJ210193_L2100219_S2_L001_R2_001.fastq.gz
-rw-r--r--    1 root     22052         2414 Jan 18 02:13 /mount/mount/QFWQQh/run-dragen-script.sh
```

**Time Started**

We can get from the task stdout

```
gds-view \
  --gds-path gds://development/temp/alexis/multiqc-1.14-testing/work/20230118_125659/logs/run_dragen_somatic_step/try-1/task-stdout-0.log \
  --to-stdout | \
head -n1
```

Yields

```
Generating run log at /var/log/dragen/dragen_run_1674008393580_7.log
```

From this we can get the first log entry

```
TZ=UTC date -d @1674008393 --iso-8601=seconds
```

Yields

```
2023-01-18T02:19:53+00:00
```

### trn.b8655dce66294249ad130a29090fce1d (new)


**Time Created**

```
ica tasks runs get trn.b8655dce66294249ad130a29090fce1d -o json | jq '.timeCreated'
```

Yields

```
"2023-02-21T10:25:30.510Z"
```

**Download Logs**

```
gds-view \
  --gds-path gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/logs/run_dragen_somatic_step/try-1/download-init-stdout-0.log \
  --to-stdout
```

Yields

```
-rw-r--r--    1 root     45684    7664401964 Feb 21 10:34 /mount/mount/data/cwl-stage-dir/stgface6780-910d-4971-ac76-8b4a4edf0868/hg38-v8-altaware-cnv-anchored.tar.gz
-rw-r--r--    1 root     45684         2414 Feb 21 10:33 /mount/mount/pePpcu/run-dragen-script.sh
-rw-r--r--    1 root     45684         1436 Feb 21 10:33 /mount/mount/pePpcu/fastq_list.csv
-rw-r--r--    1 root     45684         1436 Feb 21 10:33 /mount/mount/pePpcu/tumor_fastq_list.csv
```

**Time Started**

We can get from the task stdout

```
gds-view \
  --gds-path gds://development/temp/alexis/presigned-url-test-for-dragen-csv/work/20230221_212117/logs/run_dragen_somatic_step/try-1/task-stdout-0.log \
  --to-stdout | \
head -n1
```

Yields

```
Generating run log at /var/log/dragen/dragen_run_1676975805369_7.log
```

From this we can get the first log entry

```
TZ=UTC date -d @1676975805 --iso-8601=seconds
```

Yields

```
2023-02-21T10:36:45+00:00
```

## Conclusion

Assuming downloads to `/mount/mount` do not start until resources have been allocated, both tasks started downloads around 8-9 minutes after the task was created but the presigned urls inside the csvs start much sooner compared to the downloaded files.  This suggests that there may be some time won back by streaming the presigned urls over staging data.


| Task ID                              | Task Created | First File Staged | Last File Staged | Dragen Log Started | Total Initialisation Time (Log Starting - First File Staged) |
|--------------------------------------|--------------|-------------------|------------------|--------------------|--------------------------------------------------------------|
| trn.cf881b93a18f4e89bf9e7fcbe17f9b33 | 02:00        | 02:09             | 02:17            | 02:19              | 00:10                                                        |
| trn.b8655dce66294249ad130a29090fce1d | 10:25        | 10:33             | 10:34            | 10:36              | 00:02                                                        |

**Comment by skanwal** [comment]
> this isn't so much about inputs being optional but read1file and read2file having the capacity to be a string (presigned url), rather than a file

@alexiswl this bit was quite obvious before as well as it's clearly stated in the PR title and subsequent code updates (which, fyi, I have already reviewed and approved).

**Comment by alexiswl** [comment]
Lots of small changes here as expected, fastq-list-rows schema touches a lot of tools and workflows.

**Pull request merged**
