### PR TITLE
Updated dragen somatic tool

### PR DESCRIPTION
**Pull request by alexiswl**
1. Moved from inline js bashscript to listing (credit Yinan for discovering this potential).  
2. Added if-else statement to the end of the dragen somatic command s.t so long as the fastq list row csv looks correct, the normal bam file is renamed to match the normal's sample name with a _normal prefix
3. Keep eval under js logic since ICA doesn't handle '@' in cwl like cwl does.

### CODE REVIEW

**Comment by alexiswl** [comment]
- [ ] Waiting on `wfr.128790246e9c48f39e14d8f8ef7d868e` to complete to confirm

**Comment by alexiswl** [comment]
Outputs of `wfr.128790246e9c48f39e14d8f8ef7d868e`:

```
$ gds-ls gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/AWS-SN0_20_usage.txt
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494-replay.json
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.baf.bw
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.fastqc_metrics.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.fragment_length_hist.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.hard-filtered.baf.bw
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.hard-filtered.vcf.gz
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.hard-filtered.vcf.gz.md5sum
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.hard-filtered.vcf.gz.tbi
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.insert-stats.tab
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.mapping_metrics.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.pcr-model-0.log
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.pcr-model-1.log
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.pcr-model.log
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.ploidy.vcf.gz
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.ploidy.vcf.gz.md5sum
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.ploidy.vcf.gz.tbi
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.ploidy_estimation_metrics.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.time_metrics.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.trimmer_metrics.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.vcf.gz
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.vcf.gz.md5sum
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.vcf.gz.tbi
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.vc_metrics.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_contig_mean_cov_normal.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_contig_mean_cov_tumor.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_coverage_metrics_normal.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_coverage_metrics_tumor.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_fine_hist_normal.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_fine_hist_tumor.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_hist_normal.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_hist_tumor.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_overall_mean_cov_normal.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_overall_mean_cov_tumor.csv
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494.wgs_somatic_callable_regions.bed
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494_tumor.bam
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494_tumor.bam.bai
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180494_tumor.bam.md5sum
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180495_normal.bam
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180495_normal.bam.bai
gds://wfr.128790246e9c48f39e14d8f8ef7d868e/test-run/outputs/PRJ180494_dragen_somatic/PRJ180495_normal.bam.md5sum
```

**Comment by skanwal** [comment]
@alexiswl - LGTM.
Couple quick comments:
- do you want to register the successful workflow run for future reference?
- `# Ensure file were moving to does not exist yet` comment might need updating.

**Comment by alexiswl** [comment]
> do you want to register the successful workflow run for future reference?

Done

> # Ensure file were moving to does not exist yet comment might need updating.

This refers to the latter half of the if condition `! -f "$(inputs.output_directory)/\${new_normal_file_name_prefix}.bam"`
Have updated the comment to include the former component too.

**Review by skanwal — APPROVED** [review]

**Pull request merged**
