### PR TITLE
Adjust resource requirements for the Umccrise CWL tool

### PR DESCRIPTION
**Pull request by scwatts**
This change aligns required resources for the Umccrise CWL tool with the AWS stack [configuration](https://github.com/umccr/infrastructure/blob/cacf9e456d1d8e2b93af5476c1c7af7523a10c17/terraform/stacks/umccrise/variables.tf#L90-L105).

### CODE REVIEW

**Review by skanwal — APPROVED** [review]
LGTM!

**Comment by alexiswl** [comment]
This won't change the value of the cpu and memory, as that's bound by the segment `ilmn-tes:resources` rather than the coresMin and ramMin (used for local only or other cwltool runners), you can view the resources requirements under https://support-docs.illumina.com/SW/ICA/Content/SW/ICA/RequestResources.htm to select an appropriate size and type.

The closest I can see to your ideal requirements are:
```
standardHiCpu - small:
  cpu = 15.5
  mem = 28
  
standardHiMem - medium
  cpu = 15.5
  mem = 124
```

Is it the cpu or the memory you are most concerned about, or is it mostly to do with umccrise running fewer jobs simultaneously? If it's the latter, could we use a --threads parameter for that instead. 

```
hints:
    ResourceRequirement:
        ilmn-tes:resources:
            tier: standard
            type: standardHiCpu
            size: large
        coresMin: 16
        ramMin: 50000
```

**Comment by scwatts** [comment]
Thanks for the info. The purpose of the change was to avoid consuming more resources/credits than Umccrise needed. I had considered limiting resource usage by setting `threads` in the workflow config but afaik the workflow would still provision a 71 CPU instance.

From what I've observed, this only gives us a minimally performance benefit compared to the AWS set up, which uses 16 CPUs. Moving to a `small` or `medium` instance seems like a good fit to me. Though, if over-provisioning resources really isn't an issue of us on ICA then limiting via `--threads` is a viable option.

Did you have any concerns moving from a 71 CPU to a ~16 CPU instance?

**Comment by alexiswl** [comment]
I don't think that's an issue, but would go with the himem medium option then just in case the ram blows out

**Comment by scwatts** [comment]
Sounds good to me.

**Comment by alexiswl** [comment]
Sweet, if you commit those changes we can then re-run the github actions workflow manually to sync the definitions to ICA.

**Comment by alexiswl** [comment]
Ah sweet, that happened whilst I was typing. Re-triggering now

**Comment by scwatts** [comment]
Great, happy for this to be merged?

**Review by alexiswl — APPROVED** [review]

**Comment by alexiswl** [comment]
Yep, ah looks like when I approved it re-ran the sync command, it probably won't create any more changes. To be safe, once that's done happy for it to be merged.

**Pull request merged**
