### PR TITLE
Attempted creation of inline-csv creation for dragen-germline workflow

### PR DESCRIPTION
**Pull request by alexiswl**
Benefits: 

1. No relative path inputs - saves issues with local cwltool
2. If future WES release means that files and directories in records are staged in each tool, then the current generation of the csv will take some time as all of the fastq files will need to be downloaded into the TES task before the fastq list csv is created, even if they're not used.

Cons:
This currently doesn't work as waiting on a future WES release to solve the files and directories in records not being downloaded - see https://github.com/umccr-illumina/cwl-iap/issues/208 for more info.

### CODE REVIEW

**Comment by alexiswl** [comment]
Works with the new ICA release as shown by `wfr.a6088b4b215d4ca2b5b45f3603165e79`

**Comment by skanwal** [comment]
Nice. I have been playing with the JS code while you were on leave. 
I'll update here with my changes (mainly for logic simplification) tonight.

**Comment by alexiswl** [comment]
> I'll update here with my changes (mainly for logic simplification) tonight.

Would you mind putting it on a separate branch and then put the JS changes as a PR into this branch? 
Will be easier to see the JS changes that way.

**Comment by skanwal** [comment]
Yes, doable. I'll create a new branch with my JS code test/updates.
Though, I have been mostly testing the JS code independently. Mainly because debugging, logging and logic test is much easier outside CWL. But happy to include my changes in Dragen definition for initiating discussion.

**Comment by alexiswl** [comment]
> Though, I have been mostly testing the JS code independently

Oh nice, IDE or CLI? Have you been able to confirm it's ES5 compatible?

**Comment by skanwal** [comment]
TBH, I had to just read up on ES5.. but yes, I believe so. 
I am writing JS in VScode, which highlights syntax and the other useful stuff such as suggestions and error highlighting. Then running using `node` on CLI.

**Comment by alexiswl** [comment]
ES5 you can check by porting back to cwl and just running cwltool --validate on the tool file. Should throw a warning for anything that's not es5 compatible.

**Comment by alexiswl** [comment]
Works with `wfr.89231cc4a89446b0b7a819ea1b3d3b4c`

**Comment by alexiswl** [comment]
@skanwal this one is good to go

**Review by skanwal — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
