### PR TITLE
Added fastq_list as an optional workflow option for dragen-germline

### PR DESCRIPTION
**Pull request by alexiswl**
* Also put in check in bash script to make sure not both fastq_list_rows AND fastq_list are present

# TODO:
- [x] Merge #80 
- [x] Merge #82 
- [x] Merge #83 
- [x] Merge main into here and then test workflow and update workflow.yaml and config.yaml

### CODE REVIEW

**Comment by alexiswl** [comment]
Waiting on successful run of `wfr.3706075e05a3429c9f8c96ce90e90152`

**Comment by alexiswl** [comment]
@skanwal Ready for review

**Comment by skanwal** [comment]
Think we should also make `fastq_list_rows` [input](https://github.com/umccr/cwl-ica/blob/90d63781d7bf461328acf7c595acf5be5517b281/workflows/dragen-germline-pipeline/3.9.3/dragen-germline-pipeline__3.9.3.cwl#L42) as optional? If `fastq_list` is used as an input then `fastq_list_rows` isn't required.

**Review by skanwal — APPROVED** [review]
Thanks and approved!

**Pull request merged**
