### PR TITLE
remove ilmn-tes namespace when not used

### PR DESCRIPTION
**Pull request by alexiswl**
## Summary
Removed unnecessary ilmn-tes schema namespace in expressions.
Part B of superseding #115

## Commits
1eb0e04d7fd1d76ef4002e6e70899a67c60ff652 @mr-c Removed ilmn-tes namespace when not used 
6d07a57669cde3196f24d14d11aa1a4f3b7a0e3f @alexiswl updated dummy file tool to specify ilmn-tes resources that had not been added.

### CODE REVIEW

**Review by skanwal — APPROVED** [review]
LGTM, thank you.

**Comment by mr-c** [comment]
Thank you @alexiswl and @skanwal !

Though I still wonder about those Illumina extensions. Are they always required when running CWL on Illumina's platform? Or can the standard `ResourceRequirement` be used? If that is so, is there documentation on how that mapping works on their platform?

**Comment by alexiswl** [comment]
> Are they always required when running CWL on Illumina's platform? Or can the standard ResourceRequirement be used? If that is so, is there documentation on how that mapping works on their platform?

For fpga boards, they're definitely a requirement.  

The compute types can be found here: https://help.ica.illumina.com/project/p-flow/f-pipelines#compute-types. I don't know how it works when the ilmn resource requirement isn't specified and is not in the list of compute types provided, so I've generally just provided it to be safe but also added in the ramMin and coresMin to improve portability of other cpu tools.

**Comment by mr-c** [comment]
Yeah, the extension for FPGA makes a lot of sense. Can you ask your ICA contact about the mapping?

**Comment by pr80ik** [comment]
> Thank you @alexiswl and @skanwal !
> 
> Though I still wonder about those Illumina extensions. Are they always required when running CWL on Illumina's platform? Or can the standard `ResourceRequirement` be used? If that is so, is there documentation on how that mapping works on their platform?

the illumina extensions are not required. When CPU and Memory is specified, the engine will find the best matching instance for you that meets your cpu and/or memory requirements. If the default does not suite your needs then use the extensions to override the default.

When CPU and instance-type are both specified, the instance-type has higher priority.

You can also suppress the warning (from cwltool) about nested structure of the illumina extension by flattering it as described [here](https://help.ica.illumina.com/project/p-flow/f-pipelines/pi-cwl)

**Comment by alexiswl** [comment]
The tier extension allows a user to determine if a tool is allowed to run on a AWS spot instance right?

**Pull request merged**
