### PR TITLE
Rnasum version 0.4.2

### PR DESCRIPTION
**Pull request by alexiswl**
Moved rnasum docker repo to ghcr.io

### CODE REVIEW

**Comment by skanwal** [comment]
@alexiswl - double checking this one doesn't have any dependencies on RNAsum PRs?

**Comment by alexiswl** [comment]
> @alexiswl - double checking this one doesn't have any dependencies on RNAsum PRs?

Nope, this is using the ghcr.io release package that's in the RNASum PRs but is not waiting on them being merged.

**Review by skanwal — APPROVED** [review]

**Comment by skanwal** [comment]
@alexiswl  - before you merge, can you point me to the successful wfr ID? Just wanted to double check the report.

**Comment by alexiswl** [comment]
`wfr.0721e5d823f04808aec1c11424a902ff`

**Comment by skanwal** [comment]
All good! Noticed sync tool failing in the last PR as well.

**Comment by alexiswl** [comment]
Tokens expired, rerunning sync workflow

**Pull request merged**
