### PR TITLE
Dragen-transcriptome updates

### PR DESCRIPTION
**Pull request by alexiswl**
## Updates from v2:

* Add secondaryFiles attribute to fasta for main workflow required
* Add `lic instance id location` input to main workflow and set default in tool 
* Update create directory container to use ghcr.io registry instead
* Remove `dockerOutputDirectory` from arriba functions

## TODO
- [x] Waiting on #101

### CODE REVIEW

**Comment by skanwal** [comment]
@alexiswl - have these changes been tested in dev?

**Comment by alexiswl** [comment]
`wfr.10774ba0c18946bbb3f6e60dcb03ba4a` has succeeded as a workflow

**Review by skanwal — APPROVED** [review]

**Comment by alexiswl** [comment]
Think this issue happens when branch is not directly under main

**Comment by alexiswl** [comment]
Will merge main changes into branch and will try again, have a better solution that I've implemented with rnasum that I'll implement at some stage

**Comment by alexiswl** [comment]
Merged main into here so that means git commit should work fine now, rerunning sync action

**Pull request merged**
