### PR TITLE
Initialised dragen v4.3.6 workflows and v10 r4 datasets

### PR DESCRIPTION
**Pull request by alexiswl**
Removed create dummy file step v4.3.6 workflows

Added bunches

For transcriptome pipeline,
removed the wts multiqc input files

Upgraded to multiqc v1.25.1 as well.

Not expecting this dragen version to go into production (at least any time soon), so made really just for Min's comparison work

### CODE REVIEW

**Comment by alexiswl** [comment]
For the v10 r4 datasets we have 

* hg38 alt-masked
  * graph
  * linear
* chm13 v2 
  * graph
  * linear

**Comment by minw2828** [comment]
Hi Alexis, 

Thank you! 🙏 A scan of this looks great. I can see you are integrating the latest version of DRAGEN. 🥳

Sorry that I am on the road. I'll need somewhere quieter before I can check if all the parameters are there. 

If you have integrated all the parameters from the DRAGEN publication that Oliver sent a few days ago, and added all the parameters from this Illumina article which was published today, including the part to lower the mosaic threshold (because we have high depth for tumour samples - correct?) then we should be good to go. 

We don't have methylation for Illumina data, so leave that part in the article out. 

https://developer.illumina.com/news-updates/dragen-v4-3

Thank you very much! 🙏

Cheers,
Min

**Comment by skanwal** [comment]
@alexiswl - as discussed, I'm happy to double check and confirm all the parameters have been updated or added to this version based on these links (hopefully tomorrow).

**Comment by alexiswl** [comment]
I haven't updated any parameters, all are a copy of the dragen 4.2.4 pipelines

**Pull request merged**
